hosts_map:
- hostname: gustavs-laptop-ubuntu
  info:
    last_selected_dest: /home/user/Desktop
    mac: not used
    name: not used
  paths:
    backup_paths:
    - /home/user/Desktop/Programmieren
    - /home/user/Desktop/Arbeit
    - /home/user/Desktop/Icons_Linux
    - /home/user/Desktop/Uni_tmp
    - /home/user/Desktop/Linux_Help.txt
    - /home/user/.config/Code/User
    - /home/user/.vscode/extensions
    clean_paths:
    - /tmp
    - /home/user/.cache
    - /var/tmp
    - /var/log/
    - /home/user/.local/share/Trash/
    dest_paths:
    - /media/user/Extreme Pro/Backups/devices
    - /media/user/smb_raspberrypi/home/gazo/Desktop/cloud/Backups/devices
    - /home/user/Desktop
- hostname: gustavs-laptop-windows
  info:
    last_selected_dest: D:/Backups/devices
    mac: not used
    name: not used
  paths:
    backup_paths:
    - C:/Users/user/Desktop/Uni
    - C:/Users/user/Desktop/Icons_Windows
    - C:/Users/user/Desktop/LaTex
    - C:/Users/user/Documents/Electronic Arts/Die Sims 4
    - C:/signs
    clean_paths:
    - C:/WINDOWS/Temp
    - C:/Users/user/AppData/Local/Temp
    - C:/Users/user/Downloads
    - C:/$Recycle.Bin
    - C:/Users/user/Pictures/Screenshots
    dest_paths:
    - D:/Backups/devices
- hostname: gustavs-pc-windows
  info:
    last_selected_dest: F:/Backups/devices
    mac: not used
    name: not used
  paths:
    backup_paths:
    - C:/Users/user/Desktop/Sonstiges
    - C:/Users/user/Desktop/Freizeit
    - C:/Users/user/Desktop/Finanzen
    - C:/Users/user/AppData/Local/Google/Chrome/User Data/Default
    clean_paths:
    - C:/WINDOWS/Temp
    - C:/Users/user/AppData/Local/Temp
    - C:/Users/user/Downloads
    - C:/$Recycle.Bin
    - C:/Users/user/Pictures/Screenshots
    dest_paths:
    - /media/user/Extreme Pro/Backups/devices
    - F:/Backups/devices
- hostname: test_lin
  info:
    last_selected_dest: /home/user/Desktop/backup_test
    mac: not used
    name: not used
  paths:
    backup_paths:
    - /home/user/Desktop/Arbeit
    clean_paths: []
    dest_paths:
    - /home/user/Desktop/backup_test
- hostname: test_win
  info:
    last_selected_dest: C:/Users/user/Desktop
    mac: not used
    name: not used
  paths:
    backup_paths: []
    clean_paths: []
    dest_paths:
    - C:/Users/user/Desktop
